### PR TITLE
fix: Active Gate URL parsing

### LINKED ISSUE #832: Not possible to use Dynatrace ActiveGate REST API module with Terraform
**Describe the bug**

It is not possible to use the Terraform provider with the Dynatrace ActiveGate [REST API module](https://docs.dynatrace.com/docs/ingest-from/dynatrace-activegate/configuration/configure-activegate#api_mod).

In restricted enterprise networks with very limited access to the internet, it is common to use the Dynatrace ActiveGate with the [REST API module](https://docs.dynatrace.com/docs/ingest-from/dynatrace-activegate/configuration/configure-activegate#api_mod) enabled to comunicate with the public Dynatrace API.

**To Reproduce**

The following does not work:

```hcl
provider "dynatrace" {
  account_id = "..."

  dt_env_url   = "https://load-balancer.******.intranet:9999/e/my-environment-id"
  dt_api_token = "*****"
}
```

It seems that the Terraform provider is doing some magic URL parsing which is totally unnecessary in our case:

```
.../e/my-environment-id/e/my-environment-id/api/v2/settings/objects...
```

Image

**Expected behavior**

It should be possible to use Dynatrace ActiveGate in the intranet with the Terraform provider.

### PR DESCRIPTION
**Pull request by Kirdock**
#### **Why** this PR?
Active Gate URLs pointing to non UUID environment IDs weren't working. For `myhost:9999/e/my-env-id` the classic requests always attached another `/e/my-env-id`.

#### **What** has changed?
The URL is now correctly parsed. Active Gate URLs should work again.
The error handling for requests also slightly changed a bit. Errors of `POST/PUT/PATCH` request were swallowed. Because of this the error message pointed to the correct URL but the real request was pointing to a different one (the one with the additional `/e/env_id`).

#### **How** does it do it?
Instead of conditionally removing a URL path prefix, the initial path of the provided dt_env_url is not added again in the first place. The API client that's in use already contains this information (which host and which initial path like active gate). That's why the path was attached a second time.

#### How is it **tested**?
Added another test that checks for the correct URL

#### How does it affect **users**?
They should now be able to use Terraform when using Active Gate.

**Issue:** CA-16828, #832

### CODE REVIEW

File: dynatrace/rest/hybrid_client_test.go [hunk 1]
```diff
@@ -141,6 +147,24 @@ func TestHybridClient(t *testing.T) {
 	}
 }
 
+func TestHybridClientActiveGateRequest(t *testing.T) {
```
Comment (tomazpu) [inline dynatrace/rest/hybrid_client_test.go]: Would be nice to also add some test that fail (classic url == 0, and url.Parse fail). 

I would also add some headers to the test.

Comment (Kirdock) [reply dynatrace/rest/hybrid_client_test.go]: done 👍

**Review by tomazpu — APPROVED** [review]

**Comment by realtimetodie** [comment]
When will this bugfix be released?
